# Generated by Django 4.2 on 2025-01-14 20:28

import Cars.models
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RentalCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_company_name', models.CharField(max_length=140, verbose_name='Name')),
                ('rental_company_address', models.CharField(max_length=140, verbose_name='Address')),
                ('rental_company_phone', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('rental_company_cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_maker', models.CharField(max_length=140, verbose_name='Maker')),
                ('car_model', models.CharField(max_length=140, verbose_name='Model')),
                ('car_year', models.IntegerField(verbose_name='Year')),
                ('car_mileage', models.IntegerField(verbose_name='Mileage')),
                ('car_daily_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Daile_price')),
                ('car_color', models.CharField(max_length=140, verbose_name='Color')),
                ('car_image', stdimage.models.StdImageField(force_min_size=False, upload_to=Cars.models.get_file_path, variations={'thumb': {'crop': True, 'height': 480, 'width': 400}}, verbose_name='Image')),
                ('car_rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cars.rentalcar')),
            ],
        ),
    ]
