# Generated by Django 4.2 on 2025-01-14 20:49

import Cars.models
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_color',
            field=models.CharField(max_length=140, verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_daily_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor diário'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_image',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to=Cars.models.get_file_path, variations={'thumb': {'crop': True, 'height': 480, 'width': 400}}, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_maker',
            field=models.CharField(max_length=140, verbose_name='Fabricante'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_mileage',
            field=models.IntegerField(verbose_name='Kilometragem'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_model',
            field=models.CharField(max_length=140, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_year',
            field=models.IntegerField(verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='rentalcar',
            name='rental_company_address',
            field=models.CharField(max_length=140, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='rentalcar',
            name='rental_company_name',
            field=models.CharField(max_length=140, verbose_name='Nome da locadora'),
        ),
        migrations.AlterField(
            model_name='rentalcar',
            name='rental_company_phone',
            field=models.CharField(max_length=15, verbose_name='Telefone'),
        ),
    ]
