# Generated by Django 4.2 on 2025-01-14 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0003_alter_rentalcar_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Carro', 'verbose_name_plural': 'Carros'},
        ),
        migrations.AlterField(
            model_name='car',
            name='car_rental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cars.rentalcar', verbose_name='Locadora'),
        ),
    ]
