# Generated by Django 4.2 on 2025-01-14 21:26

import Cars.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0004_alter_car_options_alter_car_car_rental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_year',
            field=models.IntegerField(validators=[Cars.models.validate_year], verbose_name='Ano'),
        ),
    ]
